# Generated by Django 3.0.6 on 2020-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200507_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='leadtime',
            field=models.IntegerField(null=True),
        ),
    ]
